name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18.1-alpine3.15
      # env: (...)
      # ports: (...)
      # volumes: (...)
      # options: --cpus 1 --host (...)
        steps:
            - name: Log node version
              run: |
                  node -v
                  cat /etc/os-release      
     